spring.application.name=rollerSpeed
# Conexion PostgreSQL Local
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/rollerSpeed}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false