spring.application.name=rollerSpeed

# Configuración básica de DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/rollerSpeed
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Opciones JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Desactivar verificación inicial de base de datos para levantar Tomcat
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration